# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 09:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160926_0733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='original_url',
            new_name='original_uri',
        ),
    ]
