# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 07:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20160926_0944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='isValid',
            new_name='is_valid',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='isValid',
            new_name='is_valid',
        ),
    ]
