# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20160927_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='score',
        ),
        migrations.AddField(
            model_name='tag',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
