# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 13:17
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20160927_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='payload',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
