# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20160927_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_analyzed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='image',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='image',
            name='is_master',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='image',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='image',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='image',
            name='is_synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='result',
            name='feature',
            field=models.CharField(blank=True, choices=[('CA', 'Category'), ('CE', 'Celebrity'), ('DE', 'Description'), ('AD', 'Adult'), ('TE', 'Text'), ('FA', 'Face'), ('LO', 'Logo'), ('RE', 'Recognition'), ('MA', 'Map'), ('PH', 'Phone'), ('UR', 'Url')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='service',
            field=models.CharField(blank=True, choices=[('GO', 'Google Vision'), ('MI', 'Microsoft Cognitive'), ('CR', 'Craftar')], max_length=2, null=True),
        ),
    ]
