# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_image_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_sent_notification',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='result',
            name='category',
            field=models.CharField(blank=True, choices=[('AI', 'AI'), ('HU', 'Human')], default='HU', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='feature',
            field=models.CharField(blank=True, choices=[('CA', 'Category'), ('CE', 'Celebrity'), ('DE', 'Description'), ('AD', 'Adult'), ('TE', 'Text'), ('FA', 'Face'), ('LO', 'Logo'), ('RE', 'Recognition'), ('MA', 'Map'), ('PH', 'Phone'), ('UR', 'Url')], default='UR', max_length=2, null=True),
        ),
    ]
